# BlackSheep build pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- bash: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
  displayName: 'Install dependencies'

- bash: |
    make compile
  displayName: 'Compile Cython extensions'

- bash: |
    pytest --doctest-modules --junitxml=junit/test-results.xml
  displayName: 'tests'
  workingDirectory: tests
  continueOnError: true

- bash: |
   pytest --doctest-modules --junitxml=junit/test-results.xml
  workingDirectory: itests
  displayName: 'integration tests'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'publish test results **/test-results.xml'
  inputs:
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true

- bash: |
    if [ -f "build_info.txt" ]; then rm build_info.txt; fi
    echo "Build id: $(Build.BuildId)" >> build_info.txt
    echo "Build date: $(date)" >> build_info.txt
    echo "Build URL: $(Build.BuildUri)" >> build_info.txt
    echo "Build version: $(Build.DefinitionVersion)" >> build_info.txt
  displayName: 'writes build id'

- bash: |
    python setup.py sdist
  displayName: 'create artifacts'

- task: PublishBuildArtifacts@1
  displayName: 'publish dist artifacts'
  condition: and(succeeded(), eq(variables['python.version'], '3.8'))
  inputs:
    PathtoPublish: dist
    ArtifactName: dist
